# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='bag',
            name='items',
            field=models.ManyToManyField(to='bags.Item'),
        ),
    ]
