# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bags',
            field=models.ManyToManyField(to='bags.Bag'),
        ),
    ]
